package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

import java.util.Date;
// Generated Mar 3, 2015 2:32:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * EmAuditHistoryT generated by hbm2java
 */
public class EmAuditHistoryT implements java.io.Serializable {


	
	public EmAuditHistoryT() {
	}
	
	private Long id;
	private Long eauId;
	private String actionCode;
	private String comments;
	private Date createDate;
	private String createUserId;

	
	public EmAuditHistoryT(long eauId, String actionCode, Date createDate) {
		this.eauId = eauId;
		this.actionCode = actionCode;
		this.createDate = createDate;
	}

	public EmAuditHistoryT(long eauId, String actionCode, String comments,
			Date createDate, String createUserId) {
		this.eauId = eauId;
		this.actionCode = actionCode;
		this.comments = comments;
		this.createDate = createDate;
		this.createUserId = createUserId;
	}

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getEauId() {
		return this.eauId;
	}

	public void setEauId(Long eauId) {
		this.eauId = eauId;
	}

	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		EmAuditHistoryT castOther = (EmAuditHistoryT) other;

		return 
				(getId() == castOther.getId() || (getId() != null && castOther.getId() != null
				&& getId().equals(castOther.getId())))
				&& (this.getEauId() == castOther.getEauId())
				&& ((this.getActionCode() == castOther.getActionCode()) || (this
						.getActionCode() != null
						&& castOther.getActionCode() != null && this
						.getActionCode().equals(castOther.getActionCode())))
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreateUserId() == castOther.getCreateUserId()) || (this
						.getCreateUserId() != null
						&& castOther.getCreateUserId() != null && this
						.getCreateUserId().equals(castOther.getCreateUserId())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (getId() == null ? 0 : getId().hashCode());
		result = 37 * result + (int) this.getEauId().longValue();
		result = 37
				* result
				+ (getActionCode() == null ? 0 : this.getActionCode()
						.hashCode());
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37
				* result
				+ (getCreateUserId() == null ? 0 : this.getCreateUserId()
						.hashCode());
		return result;
	}


}
