package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

import java.util.Date;

/**
 * EmAuditAccountsT generated by hbm2java
 */
public class EmAuditAccountsT implements java.io.Serializable {

	private Long id;	
	private String impaciiUserId;
	private String nihNetworkId;
	private String secondaryOrgText;
	private Date createdDate;
	private String createdByUserId;
	private Date deletedDate;
	private String deletedByUserId;
	private String deactivationComments;
	private Long eauId;	
	private String firstName;
	private String lastName;
	private String createdByFullName;
	private String deletedByFullName;
	private Date lastLoginDate;
	private String inactiveUserFlag;
	private String transferToNedOrgPath;
	private String transferFromNedOrgPath;
	private String deletedTransferToOrgPath;
	private String deletedTransferFromOrgPath;
	private Date transferredDate;
	private Boolean activeCategoryFlag;
	private Boolean newCategoryFlag;
	private Boolean deletedCategoryFlag;
	private Boolean inactiveCategoryFlag;
	
	public EmAuditAccountsT() {
	}
	
	public EmAuditAccountsT(Long id, String nihNetworkId, Date createdDate, String createdByUserId, Long eauId) {
		this.id = id;
		this.nihNetworkId = nihNetworkId;
		this.createdDate = createdDate;
		this.createdByUserId = createdByUserId;
		this.eauId = eauId;
	}


	public EmAuditAccountsT(Long id, String impaciiUserId, String nihNetworkId, String secondaryOrgText,
			Date createdDate, String createdByUserId, Date deletedDate, String deletedByUserId,
			String deactivationComments, Long eauId, String firstName, String lastName, String createdByFullName,
			String deletedByFullName, Date lastLoginDate, String inactiveUserFlag, String transferToNedOrgPath,
			String transferFromNedOrgPath, Date transferredDate, String deletedTransferToOrgPath, String deletedTransferFromOrgPath, Boolean activeCategoryFlag,
			Boolean newCategoryFlag, Boolean deletedCategoryFlag, Boolean inactiveCategoryFlag) {
		super();
		this.id = id;
		this.impaciiUserId = impaciiUserId;
		this.nihNetworkId = nihNetworkId;
		this.secondaryOrgText = secondaryOrgText;
		this.createdDate = createdDate;
		this.createdByUserId = createdByUserId;
		this.deletedDate = deletedDate;
		this.deletedByUserId = deletedByUserId;
		this.deactivationComments = deactivationComments;
		this.eauId = eauId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.createdByFullName = createdByFullName;
		this.deletedByFullName = deletedByFullName;
		this.lastLoginDate = lastLoginDate;
		this.inactiveUserFlag = inactiveUserFlag;
		this.transferToNedOrgPath = transferToNedOrgPath;
		this.transferFromNedOrgPath = transferFromNedOrgPath;
		this.transferredDate = transferredDate;
		this.deletedTransferToOrgPath = deletedTransferToOrgPath;
		this.deletedTransferFromOrgPath = deletedTransferFromOrgPath;
		this.activeCategoryFlag = activeCategoryFlag;
		this.newCategoryFlag = newCategoryFlag;
		this.deletedCategoryFlag = deletedCategoryFlag;
		this.inactiveCategoryFlag = inactiveCategoryFlag;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	

	public String getImpaciiUserId() {
		return impaciiUserId;
	}

	public void setImpaciiUserId(String impaciiUserId) {
		this.impaciiUserId = impaciiUserId;
	}

	public String getNihNetworkId() {
		return nihNetworkId;
	}

	public void setNihNetworkId(String nihNetworkId) {
		this.nihNetworkId = nihNetworkId;
	}

	public String getSecondaryOrgText() {
		return secondaryOrgText;
	}

	public void setSecondaryOrgText(String secondaryOrgText) {
		this.secondaryOrgText = secondaryOrgText;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedByUserId() {
		return createdByUserId;
	}

	public void setCreatedByUserId(String createdByUserId) {
		this.createdByUserId = createdByUserId;
	}

	public Date getDeletedDate() {
		return deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	public String getDeletedByUserId() {
		return deletedByUserId;
	}

	public void setDeletedByUserId(String deletedByUserId) {
		this.deletedByUserId = deletedByUserId;
	}

	public String getDeactivationComments() {
		return deactivationComments;
	}

	public void setDeactivationComments(String deactivationComments) {
		this.deactivationComments = deactivationComments;
	}

	public Long getEauId() {
		return eauId;
	}

	public void setEauId(Long eauId) {
		this.eauId = eauId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getCreatedByFullName() {
		return createdByFullName;
	}

	public void setCreatedByFullName(String createdByFullName) {
		this.createdByFullName = createdByFullName;
	}

	public String getDeletedByFullName() {
		return deletedByFullName;
	}

	public void setDeletedByFullName(String deletedByFullName) {
		this.deletedByFullName = deletedByFullName;
	}

	public Date getLastLoginDate() {
		return lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public String getInactiveUserFlag() {
		return inactiveUserFlag;
	}

	public void setInactiveUserFlag(String inactiveUserFlag) {
		this.inactiveUserFlag = inactiveUserFlag;
	}

	public String getTransferToNedOrgPath() {
		return transferToNedOrgPath;
	}

	public void setTransferToNedOrgPath(String transferToNedOrgPath) {
		this.transferToNedOrgPath = transferToNedOrgPath;
	}

	public String getTransferFromNedOrgPath() {
		return transferFromNedOrgPath;
	}

	public void setTransferFromNedOrgPath(String transferFromNedOrgPath) {
		this.transferFromNedOrgPath = transferFromNedOrgPath;
	}

	public Date getTransferredDate() {
		return transferredDate;
	}

	public void setTransferredDate(Date transferredDate) {
		this.transferredDate = transferredDate;
	}

	public String getDeletedTransferToOrgPath() {
		return deletedTransferToOrgPath;
	}

	public void setDeletedTransferToOrgPath(String deletedTransferToOrgPath) {
		this.deletedTransferToOrgPath = deletedTransferToOrgPath;
	}

	public String getDeletedTransferFromOrgPath() {
		return deletedTransferFromOrgPath;
	}

	public void setDeletedTransferFromOrgPath(String deletedTransferFromOrgPath) {
		this.deletedTransferFromOrgPath = deletedTransferFromOrgPath;
	}
	
	public Boolean getActiveCategoryFlag() {
		return this.activeCategoryFlag;
	}

	public void setActiveCategoryFlag(Boolean activeCategoryFlag) {
		this.activeCategoryFlag = activeCategoryFlag;
	}

	public Boolean getNewCategoryFlag() {
		return this.newCategoryFlag;
	}

	public void setNewCategoryFlag(Boolean newCategoryFlag) {
		this.newCategoryFlag = newCategoryFlag;
	}

	public Boolean getDeletedCategoryFlag() {
		return this.deletedCategoryFlag;
	}

	public void setDeletedCategoryFlag(Boolean deletedCategoryFlag) {
		this.deletedCategoryFlag = deletedCategoryFlag;
	}

	public Boolean getInactiveCategoryFlag() {
		return this.inactiveCategoryFlag;
	}

	public void setInactiveCategoryFlag(Boolean inactiveCategoryFlag) {
		this.inactiveCategoryFlag = inactiveCategoryFlag;
	}
}
