package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Mar 5, 2015 1:53:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * EmAuditAccountsVw generated by hbm2java
 */
public class EmAuditAccountsVw implements java.io.Serializable {

	private Long id;
	private EmAuditsVw audit;
	private String impaciiUserId;
	private String nihNetworkId;
	private String impaciiLastName;
	private String impaciiFirstName;
	private String nedLastName;
	private String nedFirstName;
	private String nedEmailAddress;
	private String parentNedOrgPath;
	private String nedOrgPath;
	private String nedIc;
	private String nedActiveFlag;
	private String nciDoc;
	private Date createdDate;
	private String createdByUserId;
	private String createdByFullName;
	private Date deletedDate;
	private String deletedByUserId;
	private String deletedByFullName;
	private String deactivationComments;
	private String secondaryOrgText;
	private Date lastLoginDate;
	private String inactiveUserFlag;
	private List<EmAuditAccountRolesVw> accountRoles = new ArrayList<EmAuditAccountRolesVw>(0);
	private List<EmDiscrepancyTypesT> accountDiscrepancies = new ArrayList<EmDiscrepancyTypesT>(0);
	private List<EmAuditAccountActivityVw> accountActivities = new ArrayList<EmAuditAccountActivityVw>(0);
	private EmAuditAccountActivityVw accountActivity;

	public EmAuditAccountsVw() {
	}

	public EmAuditAccountsVw(Long id, EmAuditsVw audit, Date createdDate, String createdByUserId) {
		this.id = id;
		this.audit = audit;
		this.createdDate = createdDate;
		this.createdByUserId = createdByUserId;
	}

	public EmAuditAccountsVw(Long id, EmAuditsVw audit, String impaciiUserId, String nihNetworkId, String impaciiLastName, String impaciiFirstName,
			String nedLastName, String nedFirstName, String nedEmailAddress, String parentNedOrgPath, String nedOrgPath, String nedIc,
			String nedActiveFlag, String nciDoc, Date createdDate, String createdByUserId, String createdByFullName,
			Date deletedDate, String deletedByUserId, String deletedByFullName, String deactivationComments,
			String secondaryOrgText, Date lastLoginDate, String inactiveUserFlag,
			List accountRoles, List accountDiscrepancies, List accountActivities, EmAuditAccountActivityVw accountActivity) {
		this.id = id;
		this.audit = audit;
		this.impaciiUserId = impaciiUserId;
		this.nihNetworkId = nihNetworkId;
		this.impaciiLastName = impaciiLastName;
		this.impaciiFirstName = impaciiFirstName;
		this.nedLastName = nedLastName;
		this.nedFirstName = nedFirstName;
		this.nedEmailAddress = nedEmailAddress;
		this.nedOrgPath = nedOrgPath;
		this.parentNedOrgPath = parentNedOrgPath;
		this.nedIc = nedIc;
		this.nedActiveFlag = nedActiveFlag;
		this.nciDoc = nciDoc;
		this.createdDate = createdDate;
		this.createdByUserId = createdByUserId;
		this.createdByFullName = createdByFullName;
		this.deletedDate = deletedDate;
		this.deletedByUserId = deletedByUserId;
		this.deletedByFullName = deletedByFullName;
		this.deactivationComments = deactivationComments;
		this.secondaryOrgText = secondaryOrgText;
		this.lastLoginDate = lastLoginDate;
		this.inactiveUserFlag = inactiveUserFlag;
		this.accountRoles = accountRoles;
		this.accountDiscrepancies = accountDiscrepancies;
		this.setAccountActivities(accountActivities);
		this.accountActivity = accountActivity;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof EmAuditAccountsVw)) {
			return false;
		}
		EmAuditAccountsVw castOther = (EmAuditAccountsVw) other;

		return (getId() == castOther.getId() || getId() != null && castOther.getId() != null
				&& getId().equals(castOther.getId()))
				&& (getAudit() == castOther.getAudit() || getAudit() != null && castOther.getAudit() != null
				&& getAudit().equals(castOther.getAudit()))
				&& (getImpaciiUserId() == castOther.getImpaciiUserId() || getImpaciiUserId() != null
						&& castOther.getImpaciiUserId() != null
						&& getImpaciiUserId().equals(castOther.getImpaciiUserId()))
				&& (getNihNetworkId() == castOther.getNihNetworkId() || getNihNetworkId() != null
						&& castOther.getNihNetworkId() != null
						&& getNihNetworkId().equals(castOther.getNihNetworkId()))
				&& (getImpaciiLastName() == castOther.getImpaciiLastName() || getImpaciiLastName() != null
						&& castOther.getImpaciiLastName() != null
						&& getImpaciiLastName().equals(castOther.getImpaciiLastName()))
				&& (getImpaciiFirstName() == castOther.getImpaciiFirstName() || getImpaciiFirstName() != null
						&& castOther.getImpaciiFirstName() != null
						&& getImpaciiFirstName().equals(castOther.getImpaciiFirstName()))
				&& (getNedLastName() == castOther.getNedLastName() || getNedLastName() != null
						&& castOther.getNedLastName() != null && getNedLastName().equals(castOther.getNedLastName()))
				&& (getNedFirstName() == castOther.getNedFirstName() || getNedFirstName() != null
						&& castOther.getNedFirstName() != null
						&& getNedFirstName().equals(castOther.getNedFirstName()))
				&& (getNedEmailAddress() == castOther.getNedEmailAddress() || getNedEmailAddress() != null
						&& castOther.getNedEmailAddress() != null
						&& getNedEmailAddress().equals(castOther.getNedEmailAddress()))
				&& (getNedOrgPath() == castOther.getNedOrgPath() || getNedOrgPath() != null
						&& castOther.getNedOrgPath() != null && getNedOrgPath().equals(castOther.getNedOrgPath()))
				&& (getParentNedOrgPath() == castOther.getParentNedOrgPath() || getParentNedOrgPath() != null
						&& castOther.getParentNedOrgPath() != null && getParentNedOrgPath().equals(castOther.getParentNedOrgPath()))
				&& (getNedIc() == castOther.getNedIc() || getNedIc() != null && castOther.getNedIc() != null
						&& getNedIc().equals(castOther.getNedIc()))
				&& (getNedActiveFlag() == castOther.getNedActiveFlag() || getNedActiveFlag() != null
						&& castOther.getNedActiveFlag() != null
						&& getNedActiveFlag().equals(castOther.getNedActiveFlag()))
				&& (getNciDoc() == castOther.getNciDoc() || getNciDoc() != null && castOther.getNciDoc() != null
						&& getNciDoc().equals(castOther.getNciDoc()))
				&& (getCreatedDate() == castOther.getCreatedDate() || getCreatedDate() != null
						&& castOther.getCreatedDate() != null && getCreatedDate().equals(castOther.getCreatedDate()))
				&& (getCreatedByUserId() == castOther.getCreatedByUserId() || getCreatedByUserId() != null
						&& castOther.getCreatedByUserId() != null
						&& getCreatedByUserId().equals(castOther.getCreatedByUserId()))
				&& (getCreatedByFullName() == castOther.getCreatedByFullName() || getCreatedByFullName() != null
						&& castOther.getCreatedByFullName() != null
						&& getCreatedByFullName().equals(castOther.getCreatedByFullName()))
				&& (getDeletedDate() == castOther.getDeletedDate() || getDeletedDate() != null
						&& castOther.getDeletedDate() != null && getDeletedDate().equals(castOther.getDeletedDate()))
				&& (getDeletedByUserId() == castOther.getDeletedByUserId() || getDeletedByUserId() != null
						&& castOther.getDeletedByUserId() != null
						&& getDeletedByUserId().equals(castOther.getDeletedByUserId()))
				&& (getDeletedByFullName() == castOther.getDeletedByFullName() || getDeletedByFullName() != null
						&& castOther.getDeletedByFullName() != null
						&& getDeletedByFullName().equals(castOther.getDeletedByFullName()))
				&& (getDeactivationComments() == castOther.getDeactivationComments() || getDeactivationComments() != null
						&& castOther.getDeactivationComments() != null
						&& getDeactivationComments().equals(castOther.getDeactivationComments()))
				&& (getSecondaryOrgText() == castOther.getSecondaryOrgText() || getSecondaryOrgText() != null
						&& castOther.getSecondaryOrgText() != null
						&& getSecondaryOrgText().equals(castOther.getSecondaryOrgText()))
				&& (getLastLoginDate() == castOther.getLastLoginDate() || getLastLoginDate() != null
						&& castOther.getLastLoginDate() != null
						&& getLastLoginDate().equals(castOther.getLastLoginDate()))
				&& (getInactiveUserFlag() == castOther.getInactiveUserFlag() || getInactiveUserFlag() != null
						&& castOther.getInactiveUserFlag() != null
						&& getInactiveUserFlag().equals(castOther.getInactiveUserFlag()));
	}

	public EmAuditsVw getAudit() {
		return audit;
	}

	public String getCreatedByFullName() {
		return createdByFullName;
	}

	public String getCreatedByUserId() {
		return createdByUserId;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public String getDeactivationComments() {
		return deactivationComments;
	}

	public String getDeletedByFullName() {
		return deletedByFullName;
	}

	public String getDeletedByUserId() {
		return deletedByUserId;
	}

	public Date getDeletedDate() {
		return deletedDate;
	}

	public Long getId() {
		return id;
	}

	public String getImpaciiFirstName() {
		return impaciiFirstName;
	}

	public String getImpaciiLastName() {
		return impaciiLastName;
	}
	
	public String getImpaciiUserId() {
		return impaciiUserId;
	}

	public String getInactiveUserFlag() {
		return inactiveUserFlag;
	}

	public Date getLastLoginDate() {
		return lastLoginDate;
	}

	public String getNciDoc() {
		return nciDoc;
	}

	public String getNedActiveFlag() {
		return nedActiveFlag;
	}

	public String getNedEmailAddress() {
		return nedEmailAddress;
	}

	public String getNedFirstName() {
		return nedFirstName;
	}

	public String getNedIc() {
		return nedIc;
	}

	public String getNedLastName() {
		return nedLastName;
	}

	public String getNedOrgPath() {
		return nedOrgPath;
	}
	
	public String getParentNedOrgPath() {
		return parentNedOrgPath;
	}
	
	public String getNihNetworkId() {
		return nihNetworkId;
	}

	public String getSecondaryOrgText() {
		return secondaryOrgText;
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : getId().hashCode());
		result = 37 * result + (getAudit() == null ? 0 : getAudit().hashCode());
		result = 37 * result + (getImpaciiUserId() == null ? 0 : getImpaciiUserId().hashCode());
		result = 37 * result + (getNihNetworkId() == null ? 0 : getNihNetworkId().hashCode());
		result = 37 * result + (getImpaciiLastName() == null ? 0 : getImpaciiLastName().hashCode());
		result = 37 * result + (getImpaciiFirstName() == null ? 0 : getImpaciiFirstName().hashCode());
		result = 37 * result + (getNedLastName() == null ? 0 : getNedLastName().hashCode());
		result = 37 * result + (getNedFirstName() == null ? 0 : getNedFirstName().hashCode());
		result = 37 * result + (getNedEmailAddress() == null ? 0 : getNedEmailAddress().hashCode());
		result = 37 * result + (getNedOrgPath() == null ? 0 : getNedOrgPath().hashCode());
		result = 37 * result + (getParentNedOrgPath() == null ? 0 : getParentNedOrgPath().hashCode());
		result = 37 * result + (getNedIc() == null ? 0 : getNedIc().hashCode());
		result = 37 * result + (getNedActiveFlag() == null ? 0 : getNedActiveFlag().hashCode());
		result = 37 * result + (getNciDoc() == null ? 0 : getNciDoc().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : getCreatedDate().hashCode());
		result = 37 * result + (getCreatedByUserId() == null ? 0 : getCreatedByUserId().hashCode());
		result = 37 * result + (getCreatedByFullName() == null ? 0 : getCreatedByFullName().hashCode());
		result = 37 * result + (getDeletedDate() == null ? 0 : getDeletedDate().hashCode());
		result = 37 * result + (getDeletedByUserId() == null ? 0 : getDeletedByUserId().hashCode());
		result = 37 * result + (getDeletedByFullName() == null ? 0 : getDeletedByFullName().hashCode());
		result = 37 * result + (getDeactivationComments() == null ? 0 : getDeactivationComments().hashCode());
		result = 37 * result + (getSecondaryOrgText() == null ? 0 : getSecondaryOrgText().hashCode());
		result = 37 * result + (getLastLoginDate() == null ? 0 : getLastLoginDate().hashCode());
		result = 37 * result + (getInactiveUserFlag() == null ? 0 : getInactiveUserFlag().hashCode());
		return result;
	}

	public void setAudit(EmAuditsVw audit) {
		this.audit = audit;
	}

	public void setCreatedByFullName(String createdByFullName) {
		this.createdByFullName = createdByFullName;
	}

	public void setCreatedByUserId(String createdByUserId) {
		this.createdByUserId = createdByUserId;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public void setDeactivationComments(String deactivationComments) {
		this.deactivationComments = deactivationComments;
	}

	public void setDeletedByFullName(String deletedByFullName) {
		this.deletedByFullName = deletedByFullName;
	}

	public void setDeletedByUserId(String deletedByUserId) {
		this.deletedByUserId = deletedByUserId;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setImpaciiFirstName(String impaciiFirstName) {
		this.impaciiFirstName = impaciiFirstName;
	}

	public void setImpaciiLastName(String impaciiLastName) {
		this.impaciiLastName = impaciiLastName;
	}
	
	public void setImpaciiUserId(String impaciiUserId) {
		this.impaciiUserId = impaciiUserId;
	}

	public void setInactiveUserFlag(String inactiveUserFlag) {
		this.inactiveUserFlag = inactiveUserFlag;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public void setNciDoc(String nciDoc) {
		this.nciDoc = nciDoc;
	}

	public void setNedActiveFlag(String nedActiveFlag) {
		this.nedActiveFlag = nedActiveFlag;
	}

	public void setNedEmailAddress(String nedEmailAddress) {
		this.nedEmailAddress = nedEmailAddress;
	}

	public void setNedFirstName(String nedFirstName) {
		this.nedFirstName = nedFirstName;
	}

	public void setNedIc(String nedIc) {
		this.nedIc = nedIc;
	}

	public void setNedLastName(String nedLastName) {
		this.nedLastName = nedLastName;
	}

	public void setNedOrgPath(String nedOrgPath) {
		this.nedOrgPath = nedOrgPath;
	}

	public void setParentNedOrgPath(String parentNedOrgPath) {
		this.parentNedOrgPath = parentNedOrgPath;
	}
	
	public void setNihNetworkId(String nihNetworkId) {
		this.nihNetworkId = nihNetworkId;
	}

	public void setSecondaryOrgText(String secondaryOrgText) {
		this.secondaryOrgText = secondaryOrgText;
	}
	public List<EmAuditAccountRolesVw> getAccountRoles() {
		return accountRoles;
	}

	public void setAccountRoles(List<EmAuditAccountRolesVw> accountRoles) {
		this.accountRoles = accountRoles;
	}

	public List<EmDiscrepancyTypesT> getAccountDiscrepancies() {
		return accountDiscrepancies;
	}

	public void setAccountDiscrepancies(List<EmDiscrepancyTypesT> accountDiscrepancies) {
		this.accountDiscrepancies = accountDiscrepancies;
	}

	public EmAuditAccountActivityVw getAccountActivity() {
		return accountActivity;
	}

	public void setAccountActivity(EmAuditAccountActivityVw accountActivity) {
		this.accountActivity = accountActivity;
	}

	public List<EmAuditAccountActivityVw> getAccountActivities() {
		return accountActivities;
	}

	public void setAccountActivities(List<EmAuditAccountActivityVw> accountActivities) {
		this.accountActivities = accountActivities;
	}

}
