package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Mar 5, 2015 8:36:46 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmAuditAccountActivityVw generated by hbm2java
 */
public class EmAuditAccountActivityVw implements java.io.Serializable {

	private Long eaaId;
	private AppLookupT category;
	private AppLookupT action;
	private String notes;
	private String unsubmittedFlag;
	private String submittedByFullName;
	private Date submittedDate;
	private String lastChangeUserFullName;
	private Date lastChangeDate;

	public EmAuditAccountActivityVw() {
	}

	public EmAuditAccountActivityVw(Long eaaId, AppLookupT category, Date submittedDate) {
		this.eaaId = eaaId;
		this.category = category;
		this.submittedDate = submittedDate;
	}

	public EmAuditAccountActivityVw(Long eaaId, AppLookupT category, AppLookupT action, String notes,
			String unsubmittedFlag, String submittedByFullName, Date submittedDate, String lastChangeUserFullName,
			Date lastChangeDate) {
		this.eaaId = eaaId;
		this.category = category;
		this.action = action;
		this.notes = notes;
		this.unsubmittedFlag = unsubmittedFlag;
		this.submittedByFullName = submittedByFullName;
		this.submittedDate = submittedDate;
		this.lastChangeUserFullName = lastChangeUserFullName;
		this.lastChangeDate = lastChangeDate;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof EmAuditAccountActivityVw)) {
			return false;
		}
		EmAuditAccountActivityVw castOther = (EmAuditAccountActivityVw) other;

		return (getEaaId() == castOther.getEaaId() || getEaaId() != null && castOther.getEaaId() != null
				&& getEaaId().equals(castOther.getEaaId()))
				&& (getCategory() == castOther.getCategory() || getCategory() != null
						&& castOther.getCategory() != null && getCategory().equals(castOther.getCategory()))
				&& (getAction() == castOther.getAction() || getAction() != null
						&& castOther.getAction() != null && getAction().equals(castOther.getAction()))
				&& (getNotes() == castOther.getNotes() || getNotes() != null && castOther.getNotes() != null
						&& getNotes().equals(castOther.getNotes()))
				&& (getUnsubmittedFlag() == castOther.getUnsubmittedFlag() || getUnsubmittedFlag() != null
						&& castOther.getUnsubmittedFlag() != null
						&& getUnsubmittedFlag().equals(castOther.getUnsubmittedFlag()))
				&& (getSubmittedByFullName() == castOther.getSubmittedByFullName() || getSubmittedByFullName() != null
						&& castOther.getSubmittedByFullName() != null
						&& getSubmittedByFullName().equals(castOther.getSubmittedByFullName()))
				&& (getSubmittedDate() == castOther.getSubmittedDate() || getSubmittedDate() != null
						&& castOther.getSubmittedDate() != null
						&& getSubmittedDate().equals(castOther.getSubmittedDate()))
				&& (getLastChangeUserFullName() == castOther.getLastChangeUserFullName() || getLastChangeUserFullName() != null
						&& castOther.getLastChangeUserFullName() != null
						&& getLastChangeUserFullName().equals(castOther.getLastChangeUserFullName()))
				&& (getLastChangeDate() == castOther.getLastChangeDate() || getLastChangeDate() != null
						&& castOther.getLastChangeDate() != null
						&& getLastChangeDate().equals(castOther.getLastChangeDate()));
	}

	public AppLookupT getAction() {
		return action;
	}

	public AppLookupT getCategory() {
		return category;
	}

	public Long getEaaId() {
		return eaaId;
	}

	public Date getLastChangeDate() {
		return lastChangeDate;
	}

	public String getLastChangeUserFullName() {
		return lastChangeUserFullName;
	}

	public String getNotes() {
		return notes;
	}

	public String getSubmittedByFullName() {
		return submittedByFullName;
	}

	public Date getSubmittedDate() {
		return submittedDate;
	}

	public String getUnsubmittedFlag() {
		return unsubmittedFlag;
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEaaId() == null ? 0 : getEaaId().hashCode());
		result = 37 * result + (getNotes() == null ? 0 : getNotes().hashCode());
		result = 37 * result + (getUnsubmittedFlag() == null ? 0 : getUnsubmittedFlag().hashCode());
		result = 37 * result + (getSubmittedByFullName() == null ? 0 : getSubmittedByFullName().hashCode());
		result = 37 * result + (getSubmittedDate() == null ? 0 : getSubmittedDate().hashCode());
		result = 37 * result + (getLastChangeUserFullName() == null ? 0 : getLastChangeUserFullName().hashCode());
		result = 37 * result + (getLastChangeDate() == null ? 0 : getLastChangeDate().hashCode());
		return result;
	}

	public void setAction(AppLookupT action) {
		this.action = action;
	}

	public void setCategory(AppLookupT category) {
		this.category = category;
	}

	public void setEaaId(Long eaaId) {
		this.eaaId = eaaId;
	}

	public void setLastChangeDate(Date lastChangeDate) {
		this.lastChangeDate = lastChangeDate;
	}

	public void setLastChangeUserFullName(String lastChangeUserFullName) {
		this.lastChangeUserFullName = lastChangeUserFullName;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public void setSubmittedByFullName(String submittedByFullName) {
		this.submittedByFullName = submittedByFullName;
	}

	public void setSubmittedDate(Date submittedDate) {
		this.submittedDate = submittedDate;
	}

	public void setUnsubmittedFlag(String unsubmittedFlag) {
		this.unsubmittedFlag = unsubmittedFlag;
	}

}
