package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Mar 2, 2015 4:10:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmAuditHistoryVwId generated by hbm2java
 */
public class EmAuditHistoryVw implements java.io.Serializable {

	private Long auditId;
	private String actionCode;
	private Date createDate;
	private String comments;

	private String createUserFullName;

	public EmAuditHistoryVw() {
	}

	public EmAuditHistoryVw(long auditId, String actionCode, Date createDate) {
		this.auditId = auditId;
		this.actionCode = actionCode;
		this.createDate = createDate;
	}

	public EmAuditHistoryVw(long auditId, String actionCode, String comments,
			Date createDate, String createUserFullName) {
		this.auditId = auditId;
		this.actionCode = actionCode;
		this.comments = comments;
		this.createDate = createDate;
		this.createUserFullName = createUserFullName;
	}

	public Long getAuditId() {
		return this.auditId;
	}

	public void setAuditId(Long auditId) {
		this.auditId = auditId;
	}

	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUserFullName() {
		return this.createUserFullName;
	}

	public void setCreateUserFullName(String createUserFullName) {
		this.createUserFullName = createUserFullName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmAuditHistoryVw))
			return false;
		EmAuditHistoryVw castOther = (EmAuditHistoryVw) other;

		return (this.getAuditId() == castOther.getAuditId())
				&& ((this.getActionCode() == castOther.getActionCode()) || (this
						.getActionCode() != null
						&& castOther.getActionCode() != null && this
						.getActionCode().equals(castOther.getActionCode())))
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreateUserFullName() == castOther
						.getCreateUserFullName()) || (this
						.getCreateUserFullName() != null
						&& castOther.getCreateUserFullName() != null && this
						.getCreateUserFullName().equals(
								castOther.getCreateUserFullName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAuditId().longValue();
		result = 37
				* result
				+ (getActionCode() == null ? 0 : this.getActionCode()
						.hashCode());
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37
				* result
				+ (getCreateUserFullName() == null ? 0 : this
						.getCreateUserFullName().hashCode());
		return result;
	}

}
