package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Feb 26, 2015 9:49:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmAuditAccountRolesVw generated by hbm2java
 */
public class EmAuditAccountRolesVw implements java.io.Serializable {

	private Long eaaId;
	private String impaciiUserId;
	private String roleName;
	private String orgId;
	private Date createdDate;
	private String createdByUserId;
	private String createdByFullName;

	public EmAuditAccountRolesVw() {
	}

	public EmAuditAccountRolesVw(Long eaaId, String impaciiUserId, String roleName, String orgId, Date createdDate) {
		this.eaaId = eaaId;
		this.impaciiUserId = impaciiUserId;
		this.roleName = roleName;
		this.orgId = orgId;
		this.createdDate = createdDate;
	}

	public EmAuditAccountRolesVw(Long eaaId, String impaciiUserId, String roleName, String orgId, Date createdDate,
			String createdByUserId, String createdByFullName) {
		this.eaaId = eaaId;
		this.impaciiUserId = impaciiUserId;
		this.roleName = roleName;
		this.orgId = orgId;
		this.createdDate = createdDate;
		this.createdByUserId = createdByUserId;
		this.createdByFullName = createdByFullName;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof EmAuditAccountRolesVw)) {
			return false;
		}
		EmAuditAccountRolesVw castOther = (EmAuditAccountRolesVw) other;

		return (getEaaId() == castOther.getEaaId() || getEaaId() != null && castOther.getEaaId() != null
				&& getEaaId().equals(castOther.getEaaId()))
				&& (getImpaciiUserId() == castOther.getImpaciiUserId() || getImpaciiUserId() != null
						&& castOther.getImpaciiUserId() != null
						&& getImpaciiUserId().equals(castOther.getImpaciiUserId()))
				&& (getRoleName() == castOther.getRoleName() || getRoleName() != null
						&& castOther.getRoleName() != null && getRoleName().equals(castOther.getRoleName()))
				&& (getOrgId() == castOther.getOrgId() || getOrgId() != null && castOther.getOrgId() != null
						&& getOrgId().equals(castOther.getOrgId()))
				&& (getCreatedDate() == castOther.getCreatedDate() || getCreatedDate() != null
						&& castOther.getCreatedDate() != null && getCreatedDate().equals(castOther.getCreatedDate()))
				&& (getCreatedByUserId() == castOther.getCreatedByUserId() || getCreatedByUserId() != null
						&& castOther.getCreatedByUserId() != null
						&& getCreatedByUserId().equals(castOther.getCreatedByUserId()))
				&& (getCreatedByFullName() == castOther.getCreatedByFullName() || getCreatedByFullName() != null
						&& castOther.getCreatedByFullName() != null
						&& getCreatedByFullName().equals(castOther.getCreatedByFullName()));
	}

	public String getCreatedByFullName() {
		return createdByFullName;
	}

	public String getCreatedByUserId() {
		return createdByUserId;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public Long getEaaId() {
		return eaaId;
	}

	public String getImpaciiUserId() {
		return impaciiUserId;
	}

	public String getOrgId() {
		return orgId;
	}

	public String getRoleName() {
		return roleName;
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEaaId() == null ? 0 : getEaaId().hashCode());
		result = 37 * result + (getImpaciiUserId() == null ? 0 : getImpaciiUserId().hashCode());
		result = 37 * result + (getRoleName() == null ? 0 : getRoleName().hashCode());
		result = 37 * result + (getOrgId() == null ? 0 : getOrgId().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : getCreatedDate().hashCode());
		result = 37 * result + (getCreatedByUserId() == null ? 0 : getCreatedByUserId().hashCode());
		result = 37 * result + (getCreatedByFullName() == null ? 0 : getCreatedByFullName().hashCode());
		return result;
	}

	public void setCreatedByFullName(String createdByFullName) {
		this.createdByFullName = createdByFullName;
	}

	public void setCreatedByUserId(String createdByUserId) {
		this.createdByUserId = createdByUserId;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public void setEaaId(Long eaaId) {
		this.eaaId = eaaId;
	}

	public void setImpaciiUserId(String impaciiUserId) {
		this.impaciiUserId = impaciiUserId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
