package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Feb 26, 2015 9:50:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * EmAuditsVw generated by hbm2java
 */
public class EmAuditsVw implements java.io.Serializable {

	private Long id;
	private Date impaciiFromDate;
	private Date impaciiToDate = new Date();
	private Date startDate;
	private Date endDate;
	private String createUserFullName;
	private Date createDate;
	private Date i2eFromDate;
	private Date i2eToDate;
	private String activeCategoryEnabledFlag = "Y";
	private String newCategoryEnabledFlag = "Y";
	private String deletedCategoryEnabledFlag = "Y";
	private String inactiveCategoryEnabledFlag = "Y";
	
	List<EmAuditHistoryVw>  statusHistories;
	

	public EmAuditsVw() {
	}

	public EmAuditsVw(Long id, Date impaciiFromDate, Date impaciiToDate, Date startDate, Date endDate,
			String createUserFullName, Date createDate, Date i2eFromDate, Date i2eToDate, 
			List<EmAuditHistoryVw> statusHistories) {
		this.id = id;
		this.impaciiFromDate = impaciiFromDate;
		this.impaciiToDate = impaciiToDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createUserFullName = createUserFullName;
		this.createDate = createDate;
		this.i2eFromDate = i2eFromDate;
		this.i2eToDate = i2eToDate;
		this.statusHistories = statusHistories;
	}

	public EmAuditsVw(Long id, Date impaciiFromDate, Date impaciiToDate, Date startDate, String createUserFullName,
			Date i2eFromDate, Date i2eToDate) {
		this.id = id;
		this.impaciiFromDate = impaciiFromDate;
		this.impaciiToDate = impaciiToDate;
		this.startDate = startDate;
		this.createUserFullName = createUserFullName;
		this.i2eFromDate = i2eFromDate;
		this.i2eToDate = i2eToDate;
	}

	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof EmAuditsVw)) {
			return false;
		}
		EmAuditsVw castOther = (EmAuditsVw) other;

		return (getId() == castOther.getId() || getId() != null && castOther.getId() != null
				&& getId().equals(castOther.getId()))
				&& (getImpaciiFromDate() == castOther.getImpaciiFromDate() || getImpaciiFromDate() != null
						&& castOther.getImpaciiFromDate() != null
						&& getImpaciiFromDate().equals(castOther.getImpaciiFromDate()))
				&& (getImpaciiToDate() == castOther.getImpaciiToDate() || getImpaciiToDate() != null
						&& castOther.getImpaciiToDate() != null
						&& getImpaciiToDate().equals(castOther.getImpaciiToDate()))
				&& (getStartDate() == castOther.getStartDate() || getStartDate() != null
						&& castOther.getStartDate() != null && getStartDate().equals(castOther.getStartDate()))
				&& (getEndDate() == castOther.getEndDate() || getEndDate() != null && castOther.getEndDate() != null
						&& getEndDate().equals(castOther.getEndDate()))
				&& (getCreateUserFullName() == castOther.getCreateUserFullName() || getCreateUserFullName() != null
						&& castOther.getCreateUserFullName() != null
						&& getCreateUserFullName().equals(castOther.getCreateUserFullName()))
				&& (getCreateDate() == castOther.getCreateDate() || getCreateDate() != null
						&& castOther.getCreateDate() != null && getCreateDate().equals(castOther.getCreateDate()))
				&& (getI2eFromDate() == castOther.getI2eFromDate() || getI2eFromDate() != null
						&& castOther.getI2eFromDate() != null && getI2eFromDate().equals(castOther.getI2eFromDate()))
				&& (getI2eToDate() == castOther.getI2eToDate() || getI2eToDate() != null
						&& castOther.getI2eToDate() != null && getI2eToDate().equals(castOther.getI2eToDate()));
	}

	public Date getCreateDate() {
		return createDate;
	}

	public String getCreateUserFullName() {
		return createUserFullName;
	}

	public Date getEndDate() {
		return endDate;
	}

	public Date getI2eFromDate() {
		return i2eFromDate;
	}

	public Date getI2eToDate() {
		return i2eToDate;
	}

	public Long getId() {
		return id;
	}

	public Date getImpaciiFromDate() {
		return impaciiFromDate;
	}

	public Date getImpaciiToDate() {
		return impaciiToDate;
	}

	public Date getStartDate() {
		return startDate;
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : getId().hashCode());
		result = 37 * result + (getImpaciiFromDate() == null ? 0 : getImpaciiFromDate().hashCode());
		result = 37 * result + (getImpaciiToDate() == null ? 0 : getImpaciiToDate().hashCode());
		result = 37 * result + (getStartDate() == null ? 0 : getStartDate().hashCode());
		result = 37 * result + (getEndDate() == null ? 0 : getEndDate().hashCode());
		result = 37 * result + (getCreateUserFullName() == null ? 0 : getCreateUserFullName().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : getCreateDate().hashCode());
		result = 37 * result + (getI2eFromDate() == null ? 0 : getI2eFromDate().hashCode());
		result = 37 * result + (getI2eToDate() == null ? 0 : getI2eToDate().hashCode());
		return result;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public void setCreateUserFullName(String createUserFullName) {
		this.createUserFullName = createUserFullName;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setI2eFromDate(Date i2eFromDate) {
		this.i2eFromDate = i2eFromDate;
	}

	public void setI2eToDate(Date i2eToDate) {
		this.i2eToDate = i2eToDate;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setImpaciiFromDate(Date impaciiFromDate) {
		this.impaciiFromDate = impaciiFromDate;
	}

	public void setImpaciiToDate(Date impaciiToDate) {
		this.impaciiToDate = impaciiToDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * @return the activeCategoryEnabledFlag
	 */
	public String getActiveCategoryEnabledFlag() {
		return activeCategoryEnabledFlag;
	}

	/**
	 * @param activeCategoryEnabledFlag the activeCategoryEnabledFlag to set
	 */
	public void setActiveCategoryEnabledFlag(String activeCategoryEnabledFlag) {
		this.activeCategoryEnabledFlag = activeCategoryEnabledFlag;
	}

	/**
	 * @return the newCategoryEnabledFlag
	 */
	public String getNewCategoryEnabledFlag() {
		return newCategoryEnabledFlag;
	}

	/**
	 * @param newCategoryEnabledFlag the newCategoryEnabledFlag to set
	 */
	public void setNewCategoryEnabledFlag(String newCategoryEnabledFlag) {
		this.newCategoryEnabledFlag = newCategoryEnabledFlag;
	}

	/**
	 * @return the deletedCategoryEnabledFlag
	 */
	public String getDeletedCategoryEnabledFlag() {
		return deletedCategoryEnabledFlag;
	}

	/**
	 * @param deletedCategoryEnabledFlag the deletedCategoryEnabledFlag to set
	 */
	public void setDeletedCategoryEnabledFlag(String deletedCategoryEnabledFlag) {
		this.deletedCategoryEnabledFlag = deletedCategoryEnabledFlag;
	}

	/**
	 * @return the inactiveCategoryDeletedFlag
	 */
	public String getInactiveCategoryEnabledFlag() {
		return inactiveCategoryEnabledFlag;
	}

	/**
	 * @param inactiveCategoryDeletedFlag the inactiveCategoryDeletedFlag to set
	 */
	public void setInactiveCategoryEnabledFlag(String inactiveCategoryEnabledFlag) {
		this.inactiveCategoryEnabledFlag = inactiveCategoryEnabledFlag;
	}

	/**
	 * @return the statusHistories
	 */
	public List<EmAuditHistoryVw> getStatusHistories() {
		return statusHistories;
	}

	/**
	 * @param statusHistories the statusHistories to set
	 */
	public void setStatusHistories(List<EmAuditHistoryVw> statusHistories) {
		this.statusHistories = statusHistories;
	}

}
