package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Mar 2, 2015 11:26:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * EmAuditsT generated by hbm2java
 */
public class EmAuditsT implements java.io.Serializable {

	private Long id;
	private Date impaciiFromDate;
	private Date impaciiToDate;
	private Date startDate;
	private Date endDate;
	private String createUserId;
	private Date createDate;
	private Date i2eFromDate;
	private Date i2eToDate;
	
	List<EmAuditHistoryT>  statusHistories;

	public EmAuditsT() {
	}

	public EmAuditsT(Long id, Date impaciiFromDate, Date impaciiToDate,
			Date startDate, String createUserId, Date i2eFromDate,
			Date i2eToDate) {
		this.id = id;
		this.impaciiFromDate = impaciiFromDate;
		this.impaciiToDate = impaciiToDate;
		this.startDate = startDate;
		this.createUserId = createUserId;
		this.i2eFromDate = i2eFromDate;
		this.i2eToDate = i2eToDate;
	}

	public EmAuditsT(Long id, Date impaciiFromDate, Date impaciiToDate,
			Date startDate, Date endDate, String createUserId, Date createDate,
			Date i2eFromDate, Date i2eToDate) {
		this.id = id;
		this.impaciiFromDate = impaciiFromDate;
		this.impaciiToDate = impaciiToDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createUserId = createUserId;
		this.createDate = createDate;
		this.i2eFromDate = i2eFromDate;
		this.i2eToDate = i2eToDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getImpaciiFromDate() {
		return this.impaciiFromDate;
	}

	public void setImpaciiFromDate(Date impaciiFromDate) {
		this.impaciiFromDate = impaciiFromDate;
	}

	public Date getImpaciiToDate() {
		return this.impaciiToDate;
	}

	public void setImpaciiToDate(Date impaciiToDate) {
		this.impaciiToDate = impaciiToDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getI2eFromDate() {
		return this.i2eFromDate;
	}

	public void setI2eFromDate(Date i2eFromDate) {
		this.i2eFromDate = i2eFromDate;
	}

	public Date getI2eToDate() {
		return this.i2eToDate;
	}

	public void setI2eToDate(Date i2eToDate) {
		this.i2eToDate = i2eToDate;
	}
	
	/**
	 * @return the statusHistories
	 */
	public List<EmAuditHistoryT> getStatusHistories() {
		return statusHistories;
	}

	/**
	 * @param statusHistories the statusHistories to set
	 */
	public void setStatusHistories(List<EmAuditHistoryT> statusHistories) {
		this.statusHistories = statusHistories;
	}

}
