package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Jul 24, 2015 3:42:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmI2eAuditAccountRolesVw generated by hbm2java
 */
public class EmI2eAuditAccountRolesVw implements java.io.Serializable {

	private Long eiaaId;
	private Long npeId;
	private String roleCode;
	private String roleDescription;
	private Long orgId;
	private String fullOrgPathAbbrev;
	private String fullOrgPathDescription;
	private Date createdDate;
	private String createdByFullName;

	public EmI2eAuditAccountRolesVw() {
	}

	public EmI2eAuditAccountRolesVw(Long eiaaId, Long npeId, Date createdDate) {
		this.eiaaId = eiaaId;
		this.npeId = npeId;
		this.createdDate = createdDate;
	}

	public EmI2eAuditAccountRolesVw(Long eiaaId, Long npeId, String roleCode, String roleDescription,
			Long orgId, String fullOrgPathAbbrev, String fullOrgPathDescription, Date createdDate, String createdByFullName) {
		this.eiaaId = eiaaId;
		this.npeId = npeId;
		this.roleCode = roleCode;
		this.roleDescription = roleDescription;
		this.orgId = orgId;
		this.fullOrgPathAbbrev = fullOrgPathAbbrev;
		this.fullOrgPathDescription = fullOrgPathDescription;
		this.createdDate = createdDate;
		this.createdByFullName = createdByFullName;
	}

	public Long getEiaaId() {
		return this.eiaaId;
	}

	public void setEiaaId(Long eiaaId) {
		this.eiaaId = eiaaId;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public String getFullOrgPathAbbrev() {
		return this.fullOrgPathAbbrev;
	}

	public void setFullOrgPathAbbrev(String fullOrgPathAbbrev) {
		this.fullOrgPathAbbrev = fullOrgPathAbbrev;
	}

	public String getFullOrgPathDescription() {
		return this.fullOrgPathDescription;
	}

	public void setFullOrgPathDescription(String fullOrgPathDescription) {
		this.fullOrgPathDescription = fullOrgPathDescription;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Long getNpeId() {
		return npeId;
	}

	public void setNpeId(Long npeId) {
		this.npeId = npeId;
	}

	public String getCreatedByFullName() {
		return createdByFullName;
	}

	public void setCreatedByFullName(String createdByFullName) {
		this.createdByFullName = createdByFullName;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmI2eAuditAccountRolesVw))
			return false;
		EmI2eAuditAccountRolesVw castOther = (EmI2eAuditAccountRolesVw) other;

		return ((this.getEiaaId() == castOther.getEiaaId()) || (this.getEiaaId() != null
				&& castOther.getEiaaId() != null && this.getEiaaId().equals(castOther.getEiaaId())))
				&& ((this.getNpeId() == castOther.getNpeId()) || (this.getNpeId() != null
						&& castOther.getNpeId() != null && this.getNpeId().equals(castOther.getNpeId())))
				&& ((this.getRoleCode() == castOther.getRoleCode()) || (this.getRoleCode() != null
						&& castOther.getRoleCode() != null && this.getRoleCode().equals(castOther.getRoleCode())))
				&& ((this.getRoleDescription() == castOther.getRoleDescription()) || (this.getRoleDescription() != null
						&& castOther.getRoleDescription() != null && this.getRoleDescription().equals(
						castOther.getRoleDescription())))
				&& ((this.getOrgId() == castOther.getOrgId()) || (this.getOrgId() != null
						&& castOther.getOrgId() != null && this.getOrgId().equals(castOther.getOrgId())))
				&& ((this.getFullOrgPathAbbrev() == castOther.getFullOrgPathAbbrev()) || (this.getFullOrgPathAbbrev() != null
						&& castOther.getFullOrgPathAbbrev() != null && this.getFullOrgPathAbbrev().equals(
						castOther.getFullOrgPathAbbrev())))
				&& ((this.getFullOrgPathDescription() == castOther.getFullOrgPathDescription()) || (this
						.getFullOrgPathDescription() != null && castOther.getFullOrgPathDescription() != null && this
						.getFullOrgPathDescription().equals(castOther.getFullOrgPathDescription())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate()) || (this.getCreatedDate() != null
						&& castOther.getCreatedDate() != null && this.getCreatedDate().equals(
						castOther.getCreatedDate())))
				&& ((this.getCreatedByFullName() == castOther.getCreatedByFullName()) || (this
						.getCreatedByFullName() != null && castOther.getCreatedByFullName() != null && this
						.getCreatedByFullName().equals(castOther.getCreatedByFullName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEiaaId() == null ? 0 : this.getEiaaId().hashCode());
		result = 37 * result + (getNpeId() == null ? 0 : this.getNpeId().hashCode());
		result = 37 * result + (getRoleCode() == null ? 0 : this.getRoleCode().hashCode());
		result = 37 * result + (getRoleDescription() == null ? 0 : this.getRoleDescription().hashCode());
		result = 37 * result + (getOrgId() == null ? 0 : this.getOrgId().hashCode());
		result = 37 * result + (getFullOrgPathAbbrev() == null ? 0 : this.getFullOrgPathAbbrev().hashCode());
		result = 37 * result + (getFullOrgPathDescription() == null ? 0 : this.getFullOrgPathDescription().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getCreatedByFullName() == null ? 0 : this.getCreatedByFullName().hashCode());
		return result;
	}

}
