package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Jul 24, 2015 3:42:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmI2eAuditAccountsT generated by hbm2java
 */
public class EmI2eAuditAccountsT implements java.io.Serializable {

	private Long id;
	private Long npnId;
	private String lastName;
	private String firstName;
	private String nihNetworkId;
	private Date createdDate;
	private String createdByUserId;
	private String lastChangeUserId;
	private Long eauId;
	private Long actionId;
	private String lastSubmittedByUserId;
	private Date lastSubmittedDate;
	private String notes;
	private String unsubmittedFlag;
	private String actionCreateUserId;
	private Date actionCreateDate;
	private String oracleId;
	private Date inactiveDate;

	public EmI2eAuditAccountsT() {
	}

	public EmI2eAuditAccountsT(Long id, Long npnId, Date createdDate, String createdByUserId, Long eauId) {
		this.id = id;
		this.npnId = npnId;
		this.createdDate = createdDate;
		this.createdByUserId = createdByUserId;
		this.eauId = eauId;
	}

	public EmI2eAuditAccountsT(Long id, Long npnId, String lastName, String firstName, String nihNetworkId,
			Date createdDate, String createdByUserId, String lastChangeUserId, Long eauId, Long actionId,
			String lastSubmittedByUserId, Date lastSubmittedDate, String notes, String unsubmittedFlag,
			String actionCreateUserId, Date actionCreateDate, String oracleId, Date inactiveDate) {
		this.id = id;
		this.npnId = npnId;
		this.lastName = lastName;
		this.firstName = firstName;
		this.nihNetworkId = nihNetworkId;
		this.createdDate = createdDate;
		this.createdByUserId = createdByUserId;
		this.lastChangeUserId = lastChangeUserId;
		this.eauId = eauId;
		this.actionId = actionId;
		this.lastSubmittedByUserId = lastSubmittedByUserId;
		this.lastSubmittedDate = lastSubmittedDate;
		this.notes = notes;
		this.unsubmittedFlag = unsubmittedFlag;
		this.actionCreateUserId = actionCreateUserId;
		this.actionCreateDate = actionCreateDate;
		this.oracleId = oracleId;
		this.inactiveDate = inactiveDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getNpnId() {
		return this.npnId;
	}

	public void setNpnId(Long npnId) {
		this.npnId = npnId;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getNihNetworkId() {
		return this.nihNetworkId;
	}

	public void setNihNetworkId(String nihNetworkId) {
		this.nihNetworkId = nihNetworkId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedByUserId() {
		return this.createdByUserId;
	}

	public void setCreatedByUserId(String createdByUserId) {
		this.createdByUserId = createdByUserId;
	}

	public String getLastChangeUserId() {
		return this.lastChangeUserId;
	}

	public void setLastChangeUserId(String lastChangeUserId) {
		this.lastChangeUserId = lastChangeUserId;
	}

	public Long getEauId() {
		return this.eauId;
	}

	public void setEauId(Long eauId) {
		this.eauId = eauId;
	}

	public Long getActionId() {
		return this.actionId;
	}

	public void setActionId(Long actionId) {
		this.actionId = actionId;
	}

	public String getLastSubmittedByUserId() {
		return this.lastSubmittedByUserId;
	}

	public void setLastSubmittedByUserId(String lastSubmittedByUserId) {
		this.lastSubmittedByUserId = lastSubmittedByUserId;
	}

	public Date getLastSubmittedDate() {
		return this.lastSubmittedDate;
	}

	public void setLastSubmittedDate(Date lastSubmittedDate) {
		this.lastSubmittedDate = lastSubmittedDate;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getUnsubmittedFlag() {
		return this.unsubmittedFlag;
	}

	public void setUnsubmittedFlag(String unsubmittedFlag) {
		this.unsubmittedFlag = unsubmittedFlag;
	}

	public String getActionCreateUserId() {
		return this.actionCreateUserId;
	}

	public void setActionCreateUserId(String actionCreateUserId) {
		this.actionCreateUserId = actionCreateUserId;
	}

	public Date getActionCreateDate() {
		return this.actionCreateDate;
	}

	public void setActionCreateDate(Date actionCreateDate) {
		this.actionCreateDate = actionCreateDate;
	}

	public String getOracleId() {
		return this.oracleId;
	}

	public void setOracleId(String oracleId) {
		this.oracleId = oracleId;
	}

	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

}
