package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Mar 10, 2015 4:08:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * EmOrganizationVw generated by hbm2java
 */
public class EmOrganizationVw implements java.io.Serializable {

	private String nihorgpath;

	public EmOrganizationVw() {
	}

	public EmOrganizationVw(String nihorgpath) {
		this.nihorgpath = nihorgpath;
	}

	public String getNihorgpath() {
		return this.nihorgpath;
	}

	public void setNihorgpath(String nihorgpath) {
		this.nihorgpath = nihorgpath;
	}

}
