package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Jun 30, 2015 2:45:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * EmPortfolioI2eVw generated by hbm2java
 */
public class EmPortfolioI2eVw implements java.io.Serializable {

	private Long npnId;
	private String oracleId;
	private String nihNetworkId;
	private String lastName;
	private String firstName;
	private String i2eLastName;
	private String i2eFirstName;
	private String nedLastName;
	private String nedFirstName;
	private String nedEmailAddress;
	private String parentNedOrgPath;
	private String nedOrgPath;
	private String nedIc;
	private String nedActiveFlag;
	private String nciDoc;
	private Date createdDate;
	private String lastUpdByFullName;
	private String i2eOnlyFlag;
	private String notes;
	private String notesSubmittedByFullName;
	private Date notesSubmittedDate;
	private List<I2eActiveUserRolesVw> accountRoles = new ArrayList<I2eActiveUserRolesVw>(0);
	
	public EmPortfolioI2eVw() {
	}

	public EmPortfolioI2eVw(Long npnId, String i2eLastName, String i2eFirstName, Date createdDate) {
		this.npnId = npnId;
		this.i2eLastName = i2eLastName;
		this.i2eFirstName = i2eFirstName;
		this.createdDate = createdDate;
	}

	public EmPortfolioI2eVw(Long npnId, String oracleId, String nihNetworkId, String lastName, String firstName,
			String i2eLastName, String i2eFirstName, String nedLastName, String nedFirstName, String nedEmailAddress,
			String parentNedOrgPath, String nedOrgPath, String nedIc, String nedActiveFlag, String nciDoc,
			Date createdDate, String lastUpdByFullName, String i2eOnlyFlag, String notes,
			String notesSubmittedByFullName, Date notesSubmittedDate, List accountRoles) {
		this.npnId = npnId;
		this.oracleId = oracleId;
		this.nihNetworkId = nihNetworkId;
		this.lastName = lastName;
		this.firstName = firstName;
		this.i2eLastName = i2eLastName;
		this.i2eFirstName = i2eFirstName;
		this.nedLastName = nedLastName;
		this.nedFirstName = nedFirstName;
		this.nedEmailAddress = nedEmailAddress;
		this.parentNedOrgPath = parentNedOrgPath;
		this.nedOrgPath = nedOrgPath;
		this.nedIc = nedIc;
		this.nedActiveFlag = nedActiveFlag;
		this.nciDoc = nciDoc;
		this.createdDate = createdDate;
		this.lastUpdByFullName = lastUpdByFullName;
		this.i2eOnlyFlag = i2eOnlyFlag;
		this.notes = notes;
		this.notesSubmittedByFullName = notesSubmittedByFullName;
		this.notesSubmittedDate = notesSubmittedDate;
		this.accountRoles = accountRoles;
	}

	public Long getNpnId() {
		return this.npnId;
	}

	public void setNpnId(Long npnId) {
		this.npnId = npnId;
	}

	public String getOracleId() {
		return this.oracleId;
	}

	public void setOracleId(String oracleId) {
		this.oracleId = oracleId;
	}

	public String getNihNetworkId() {
		return this.nihNetworkId;
	}

	public void setNihNetworkId(String nihNetworkId) {
		this.nihNetworkId = nihNetworkId;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getI2eLastName() {
		return this.i2eLastName;
	}

	public void setI2eLastName(String i2eLastName) {
		this.i2eLastName = i2eLastName;
	}

	public String getI2eFirstName() {
		return this.i2eFirstName;
	}

	public void setI2eFirstName(String i2eFirstName) {
		this.i2eFirstName = i2eFirstName;
	}

	public String getNedLastName() {
		return this.nedLastName;
	}

	public void setNedLastName(String nedLastName) {
		this.nedLastName = nedLastName;
	}

	public String getNedFirstName() {
		return this.nedFirstName;
	}

	public void setNedFirstName(String nedFirstName) {
		this.nedFirstName = nedFirstName;
	}

	public String getNedEmailAddress() {
		return this.nedEmailAddress;
	}

	public void setNedEmailAddress(String nedEmailAddress) {
		this.nedEmailAddress = nedEmailAddress;
	}

	public String getParentNedOrgPath() {
		return this.parentNedOrgPath;
	}

	public void setParentNedOrgPath(String parentNedOrgPath) {
		this.parentNedOrgPath = parentNedOrgPath;
	}

	public String getNedOrgPath() {
		return this.nedOrgPath;
	}

	public void setNedOrgPath(String nedOrgPath) {
		this.nedOrgPath = nedOrgPath;
	}

	public String getNedIc() {
		return this.nedIc;
	}

	public void setNedIc(String nedIc) {
		this.nedIc = nedIc;
	}

	public String getNedActiveFlag() {
		return this.nedActiveFlag;
	}

	public void setNedActiveFlag(String nedActiveFlag) {
		this.nedActiveFlag = nedActiveFlag;
	}

	public String getNciDoc() {
		return this.nciDoc;
	}

	public void setNciDoc(String nciDoc) {
		this.nciDoc = nciDoc;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastUpdByFullName() {
		return this.lastUpdByFullName;
	}

	public void setLastUpdByFullName(String lastUpdByFullName) {
		this.lastUpdByFullName = lastUpdByFullName;
	}

	public String getI2eOnlyFlag() {
		return this.i2eOnlyFlag;
	}

	public void setI2eOnlyFlag(String i2eOnlyFlag) {
		this.i2eOnlyFlag = i2eOnlyFlag;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getNotesSubmittedByFullName() {
		return this.notesSubmittedByFullName;
	}

	public void setNotesSubmittedByFullName(String notesSubmittedByFullName) {
		this.notesSubmittedByFullName = notesSubmittedByFullName;
	}

	public Date getNotesSubmittedDate() {
		return this.notesSubmittedDate;
	}

	public void setNotesSubmittedDate(Date notesSubmittedDate) {
		this.notesSubmittedDate = notesSubmittedDate;
	}

	public List<I2eActiveUserRolesVw> getAccountRoles() {
		return accountRoles;
	}

	public void setAccountRoles(List<I2eActiveUserRolesVw> accountRoles) {
		this.accountRoles = accountRoles;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmPortfolioI2eVw))
			return false;
		EmPortfolioI2eVw castOther = (EmPortfolioI2eVw) other;

		return ((this.getNpnId() == castOther.getNpnId()) || (this.getNpnId() != null && castOther.getNpnId() != null && this
				.getNpnId().equals(castOther.getNpnId())))
				&& ((this.getOracleId() == castOther.getOracleId()) || (this.getOracleId() != null
						&& castOther.getOracleId() != null && this.getOracleId().equals(castOther.getOracleId())))
				&& ((this.getNihNetworkId() == castOther.getNihNetworkId()) || (this.getNihNetworkId() != null
						&& castOther.getNihNetworkId() != null && this.getNihNetworkId().equals(
						castOther.getNihNetworkId())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null
						&& castOther.getLastName() != null && this.getLastName().equals(castOther.getLastName())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
						&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getI2eLastName() == castOther.getI2eLastName()) || (this.getI2eLastName() != null
						&& castOther.getI2eLastName() != null && this.getI2eLastName().equals(
						castOther.getI2eLastName())))
				&& ((this.getI2eFirstName() == castOther.getI2eFirstName()) || (this.getI2eFirstName() != null
						&& castOther.getI2eFirstName() != null && this.getI2eFirstName().equals(
						castOther.getI2eFirstName())))
				&& ((this.getNedLastName() == castOther.getNedLastName()) || (this.getNedLastName() != null
						&& castOther.getNedLastName() != null && this.getNedLastName().equals(
						castOther.getNedLastName())))
				&& ((this.getNedFirstName() == castOther.getNedFirstName()) || (this.getNedFirstName() != null
						&& castOther.getNedFirstName() != null && this.getNedFirstName().equals(
						castOther.getNedFirstName())))
				&& ((this.getNedEmailAddress() == castOther.getNedEmailAddress()) || (this.getNedEmailAddress() != null
						&& castOther.getNedEmailAddress() != null && this.getNedEmailAddress().equals(
						castOther.getNedEmailAddress())))
				&& ((this.getParentNedOrgPath() == castOther.getParentNedOrgPath()) || (this.getParentNedOrgPath() != null
						&& castOther.getParentNedOrgPath() != null && this.getParentNedOrgPath().equals(
						castOther.getParentNedOrgPath())))
				&& ((this.getNedOrgPath() == castOther.getNedOrgPath()) || (this.getNedOrgPath() != null
						&& castOther.getNedOrgPath() != null && this.getNedOrgPath().equals(castOther.getNedOrgPath())))
				&& ((this.getNedIc() == castOther.getNedIc()) || (this.getNedIc() != null
						&& castOther.getNedIc() != null && this.getNedIc().equals(castOther.getNedIc())))
				&& ((this.getNedActiveFlag() == castOther.getNedActiveFlag()) || (this.getNedActiveFlag() != null
						&& castOther.getNedActiveFlag() != null && this.getNedActiveFlag().equals(
						castOther.getNedActiveFlag())))
				&& ((this.getNciDoc() == castOther.getNciDoc()) || (this.getNciDoc() != null
						&& castOther.getNciDoc() != null && this.getNciDoc().equals(castOther.getNciDoc())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate()) || (this.getCreatedDate() != null
						&& castOther.getCreatedDate() != null && this.getCreatedDate().equals(
						castOther.getCreatedDate())))
				&& ((this.getLastUpdByFullName() == castOther.getLastUpdByFullName()) || (this.getLastUpdByFullName() != null
						&& castOther.getLastUpdByFullName() != null && this.getLastUpdByFullName().equals(
						castOther.getLastUpdByFullName())))
				&& ((this.getI2eOnlyFlag() == castOther.getI2eOnlyFlag()) || (this.getI2eOnlyFlag() != null
						&& castOther.getI2eOnlyFlag() != null && this.getI2eOnlyFlag().equals(
						castOther.getI2eOnlyFlag())))
				&& ((this.getNotes() == castOther.getNotes()) || (this.getNotes() != null
						&& castOther.getNotes() != null && this.getNotes().equals(castOther.getNotes())))
				&& ((this.getNotesSubmittedByFullName() == castOther.getNotesSubmittedByFullName()) || (this
						.getNotesSubmittedByFullName() != null && castOther.getNotesSubmittedByFullName() != null && this
						.getNotesSubmittedByFullName().equals(castOther.getNotesSubmittedByFullName())))
				&& ((this.getNotesSubmittedDate() == castOther.getNotesSubmittedDate()) || (this
						.getNotesSubmittedDate() != null && castOther.getNotesSubmittedDate() != null && this
						.getNotesSubmittedDate().equals(castOther.getNotesSubmittedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNpnId() == null ? 0 : this.getNpnId().hashCode());
		result = 37 * result + (getOracleId() == null ? 0 : this.getOracleId().hashCode());
		result = 37 * result + (getNihNetworkId() == null ? 0 : this.getNihNetworkId().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getI2eLastName() == null ? 0 : this.getI2eLastName().hashCode());
		result = 37 * result + (getI2eFirstName() == null ? 0 : this.getI2eFirstName().hashCode());
		result = 37 * result + (getNedLastName() == null ? 0 : this.getNedLastName().hashCode());
		result = 37 * result + (getNedFirstName() == null ? 0 : this.getNedFirstName().hashCode());
		result = 37 * result + (getNedEmailAddress() == null ? 0 : this.getNedEmailAddress().hashCode());
		result = 37 * result + (getParentNedOrgPath() == null ? 0 : this.getParentNedOrgPath().hashCode());
		result = 37 * result + (getNedOrgPath() == null ? 0 : this.getNedOrgPath().hashCode());
		result = 37 * result + (getNedIc() == null ? 0 : this.getNedIc().hashCode());
		result = 37 * result + (getNedActiveFlag() == null ? 0 : this.getNedActiveFlag().hashCode());
		result = 37 * result + (getNciDoc() == null ? 0 : this.getNciDoc().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getLastUpdByFullName() == null ? 0 : this.getLastUpdByFullName().hashCode());
		result = 37 * result + (getI2eOnlyFlag() == null ? 0 : this.getI2eOnlyFlag().hashCode());
		result = 37 * result + (getNotes() == null ? 0 : this.getNotes().hashCode());
		result = 37 * result
				+ (getNotesSubmittedByFullName() == null ? 0 : this.getNotesSubmittedByFullName().hashCode());
		result = 37 * result + (getNotesSubmittedDate() == null ? 0 : this.getNotesSubmittedDate().hashCode());
		return result;
	}

}
