package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Jun 30, 2015 2:45:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmPortfolioNotesT generated by hbm2java
 */
public class EmPortfolioNotesT implements java.io.Serializable {

	private String impaciiUserId;
	private String notes;
	private String createUserId;
	private Date createDate;
	private String lastChangeUserId;
	private Date lastChangeDate;
	private Long npnId;

	public EmPortfolioNotesT() {
	}

	public EmPortfolioNotesT(String impaciiUserId, String createUserId, Date createDate) {
		this.impaciiUserId = impaciiUserId;
		this.createUserId = createUserId;
		this.createDate = createDate;
	}

	public EmPortfolioNotesT(String impaciiUserId, String notes, String createUserId, Date createDate,
			String lastChangeUserId, Date lastChangeDate, Long npnId) {
		this.impaciiUserId = impaciiUserId;
		this.notes = notes;
		this.createUserId = createUserId;
		this.createDate = createDate;
		this.lastChangeUserId = lastChangeUserId;
		this.lastChangeDate = lastChangeDate;
		this.npnId = npnId;
	}

	public String getImpaciiUserId() {
		return this.impaciiUserId;
	}

	public void setImpaciiUserId(String impaciiUserId) {
		this.impaciiUserId = impaciiUserId;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getLastChangeUserId() {
		return this.lastChangeUserId;
	}

	public void setLastChangeUserId(String lastChangeUserId) {
		this.lastChangeUserId = lastChangeUserId;
	}

	public Date getLastChangeDate() {
		return this.lastChangeDate;
	}

	public void setLastChangeDate(Date lastChangeDate) {
		this.lastChangeDate = lastChangeDate;
	}

	public Long getNpnId() {
		return this.npnId;
	}

	public void setNpnId(Long npnId) {
		this.npnId = npnId;
	}

}
