package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Mar 4, 2015 12:05:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EmPortfolioRolesVw generated by hbm2java
 */
public class EmPortfolioRolesVw implements java.io.Serializable {

	private String impaciiUserId;
	private String roleName;
	private String orgId;
	private Date createdDate;
	private String createdByUserId;
	private String createdByFullName;

	public EmPortfolioRolesVw() {
	}

	public EmPortfolioRolesVw(String impaciiUserId, String roleName, Date createdDate, String createdByUserId) {
		this.impaciiUserId = impaciiUserId;
		this.roleName = roleName;
		this.createdDate = createdDate;
		this.createdByUserId = createdByUserId;
	}

	public EmPortfolioRolesVw(String impaciiUserId, String roleName, String orgId, Date createdDate,
			String createdByUserId, String createdByFullName) {
		this.impaciiUserId = impaciiUserId;
		this.roleName = roleName;
		this.orgId = orgId;
		this.createdDate = createdDate;
		this.createdByUserId = createdByUserId;
		this.createdByFullName = createdByFullName;
	}

	public String getImpaciiUserId() {
		return this.impaciiUserId;
	}

	public void setImpaciiUserId(String impaciiUserId) {
		this.impaciiUserId = impaciiUserId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getOrgId() {
		return this.orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedByUserId() {
		return this.createdByUserId;
	}

	public void setCreatedByUserId(String createdByUserId) {
		this.createdByUserId = createdByUserId;
	}

	public String getCreatedByFullName() {
		return this.createdByFullName;
	}

	public void setCreatedByFullName(String createdByFullName) {
		this.createdByFullName = createdByFullName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmPortfolioRolesVw))
			return false;
		EmPortfolioRolesVw castOther = (EmPortfolioRolesVw) other;

		return ((this.getImpaciiUserId() == castOther.getImpaciiUserId()) || (this.getImpaciiUserId() != null
				&& castOther.getImpaciiUserId() != null && this.getImpaciiUserId()
				.equals(castOther.getImpaciiUserId())))
				&& ((this.getRoleName() == castOther.getRoleName()) || (this.getRoleName() != null
						&& castOther.getRoleName() != null && this.getRoleName().equals(castOther.getRoleName())))
				&& ((this.getOrgId() == castOther.getOrgId()) || (this.getOrgId() != null
						&& castOther.getOrgId() != null && this.getOrgId().equals(castOther.getOrgId())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate()) || (this.getCreatedDate() != null
						&& castOther.getCreatedDate() != null && this.getCreatedDate().equals(
						castOther.getCreatedDate())))
				&& ((this.getCreatedByUserId() == castOther.getCreatedByUserId()) || (this.getCreatedByUserId() != null
						&& castOther.getCreatedByUserId() != null && this.getCreatedByUserId().equals(
						castOther.getCreatedByUserId())))
				&& ((this.getCreatedByFullName() == castOther.getCreatedByFullName()) || (this.getCreatedByFullName() != null
						&& castOther.getCreatedByFullName() != null && this.getCreatedByFullName().equals(
						castOther.getCreatedByFullName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getImpaciiUserId() == null ? 0 : this.getImpaciiUserId().hashCode());
		result = 37 * result + (getRoleName() == null ? 0 : this.getRoleName().hashCode());
		result = 37 * result + (getOrgId() == null ? 0 : this.getOrgId().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getCreatedByUserId() == null ? 0 : this.getCreatedByUserId().hashCode());
		result = 37 * result + (getCreatedByFullName() == null ? 0 : this.getCreatedByFullName().hashCode());
		return result;
	}

}
