package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Mar 19, 2015 9:54:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * EraBusinessRolesMv generated by hbm2java
 */
public class EraBusinessRolesMv implements java.io.Serializable {

	private String code;
	private String descrip;

	public EraBusinessRolesMv() {
	}

	public EraBusinessRolesMv(String code) {
		this.code = code;
	}

	public EraBusinessRolesMv(String code, String descrip) {
		this.code = code;
		this.descrip = descrip;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

}
