package gov.nih.nci.cbiit.scimgmt.entmaint.hibernate;

// Generated Jun 30, 2015 2:45:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * I2eActiveUserRolesVw generated by hbm2java
 */
public class I2eActiveUserRolesVw implements java.io.Serializable {

	private String oracleId;
	private String nciLdapCn;
	private Long npnId;
	private Long npeId;
	private String roleCode;
	private String roleName;
	private Date roleCreatedDate;
	private Long orgId;
	private String orgAbbrev;
	private String docAbbrev;
	private String ldapRoleName;
	private Long ogaBranchId;

	public I2eActiveUserRolesVw() {
	}

	public I2eActiveUserRolesVw(Long npnId, Long npeId, String roleCode, String roleName,
			Date roleCreatedDate, Long orgId) {
		this.npnId = npnId;
		this.npeId = npeId;
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.roleCreatedDate = roleCreatedDate;
		this.orgId = orgId;
	}

	public I2eActiveUserRolesVw(String oracleId, String nciLdapCn, Long npnId, Long npeId, String roleCode,
			String roleName, Date roleCreatedDate, Long orgId, String orgAbbrev, String docAbbrev,
			String ldapRoleName, Long ogaBranchId) {
		this.oracleId = oracleId;
		this.nciLdapCn = nciLdapCn;
		this.npnId = npnId;
		this.npeId = npeId;
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.roleCreatedDate = roleCreatedDate;
		this.orgId = orgId;
		this.orgAbbrev = orgAbbrev;
		this.docAbbrev = docAbbrev;
		this.ldapRoleName = ldapRoleName;
		this.ogaBranchId = ogaBranchId;
	}

	public String getOracleId() {
		return this.oracleId;
	}

	public void setOracleId(String oracleId) {
		this.oracleId = oracleId;
	}

	public String getNciLdapCn() {
		return this.nciLdapCn;
	}

	public void setNciLdapCn(String nciLdapCn) {
		this.nciLdapCn = nciLdapCn;
	}

	public Long getNpnId() {
		return this.npnId;
	}

	public void setNpnId(Long npnId) {
		this.npnId = npnId;
	}

	public Long getNpeId() {
		return this.npeId;
	}

	public void setNpeId(Long npeId) {
		this.npeId = npeId;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Date getRoleCreatedDate() {
		return this.roleCreatedDate;
	}

	public void setRoleCreatedDate(Date roleCreatedDate) {
		this.roleCreatedDate = roleCreatedDate;
	}

	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public String getOrgAbbrev() {
		return this.orgAbbrev;
	}

	public void setOrgAbbrev(String orgAbbrev) {
		this.orgAbbrev = orgAbbrev;
	}

	public String getDocAbbrev() {
		return this.docAbbrev;
	}

	public void setDocAbbrev(String docAbbrev) {
		this.docAbbrev = docAbbrev;
	}

	public String getLdapRoleName() {
		return this.ldapRoleName;
	}

	public void setLdapRoleName(String ldapRoleName) {
		this.ldapRoleName = ldapRoleName;
	}

	public Long getOgaBranchId() {
		return this.ogaBranchId;
	}

	public void setOgaBranchId(Long ogaBranchId) {
		this.ogaBranchId = ogaBranchId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof I2eActiveUserRolesVw))
			return false;
		I2eActiveUserRolesVw castOther = (I2eActiveUserRolesVw) other;

		return ((this.getOracleId() == castOther.getOracleId()) || (this.getOracleId() != null
				&& castOther.getOracleId() != null && this.getOracleId().equals(castOther.getOracleId())))
				&& ((this.getNciLdapCn() == castOther.getNciLdapCn()) || (this.getNciLdapCn() != null
						&& castOther.getNciLdapCn() != null && this.getNciLdapCn().equals(castOther.getNciLdapCn())))
				&& ((this.getNpnId() == castOther.getNpnId()) || (this.getNpnId() != null
						&& castOther.getNpnId() != null && this.getNpnId().equals(castOther.getNpnId())))
				&& ((this.getNpeId() == castOther.getNpeId()) || (this.getNpeId() != null
						&& castOther.getNpeId() != null && this.getNpeId().equals(castOther.getNpeId())))
				&& ((this.getRoleCode() == castOther.getRoleCode()) || (this.getRoleCode() != null
						&& castOther.getRoleCode() != null && this.getRoleCode().equals(castOther.getRoleCode())))
				&& ((this.getRoleName() == castOther.getRoleName()) || (this.getRoleName() != null
						&& castOther.getRoleName() != null && this.getRoleName().equals(castOther.getRoleName())))
				&& ((this.getRoleCreatedDate() == castOther.getRoleCreatedDate()) || (this.getRoleCreatedDate() != null
						&& castOther.getRoleCreatedDate() != null && this.getRoleCreatedDate().equals(
						castOther.getRoleCreatedDate())))
				&& ((this.getOrgId() == castOther.getOrgId()) || (this.getOrgId() != null
						&& castOther.getOrgId() != null && this.getOrgId().equals(castOther.getOrgId())))
				&& ((this.getOrgAbbrev() == castOther.getOrgAbbrev()) || (this.getOrgAbbrev() != null
						&& castOther.getOrgAbbrev() != null && this.getOrgAbbrev().equals(castOther.getOrgAbbrev())))
				&& ((this.getDocAbbrev() == castOther.getDocAbbrev()) || (this.getDocAbbrev() != null
						&& castOther.getDocAbbrev() != null && this.getDocAbbrev().equals(castOther.getDocAbbrev())))
				&& ((this.getLdapRoleName() == castOther.getLdapRoleName()) || (this.getLdapRoleName() != null
						&& castOther.getLdapRoleName() != null && this.getLdapRoleName().equals(
						castOther.getLdapRoleName())))
				&& ((this.getOgaBranchId() == castOther.getOgaBranchId()) || (this.getOgaBranchId() != null
						&& castOther.getOgaBranchId() != null && this.getOgaBranchId().equals(
						castOther.getOgaBranchId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOracleId() == null ? 0 : this.getOracleId().hashCode());
		result = 37 * result + (getNciLdapCn() == null ? 0 : this.getNciLdapCn().hashCode());
		result = 37 * result + (getNpnId() == null ? 0 : this.getNpnId().hashCode());
		result = 37 * result + (getNpeId() == null ? 0 : this.getNpeId().hashCode());
		result = 37 * result + (getRoleCode() == null ? 0 : this.getRoleCode().hashCode());
		result = 37 * result + (getRoleName() == null ? 0 : this.getRoleName().hashCode());
		result = 37 * result + (getRoleCreatedDate() == null ? 0 : this.getRoleCreatedDate().hashCode());
		result = 37 * result + (getOrgId() == null ? 0 : this.getOrgId().hashCode());
		result = 37 * result + (getOrgAbbrev() == null ? 0 : this.getOrgAbbrev().hashCode());
		result = 37 * result + (getDocAbbrev() == null ? 0 : this.getDocAbbrev().hashCode());
		result = 37 * result + (getLdapRoleName() == null ? 0 : this.getLdapRoleName().hashCode());
		result = 37 * result + (getOgaBranchId() == null ? 0 : this.getOgaBranchId().hashCode());
		return result;
	}

}
